try {
    throw new Error('Algo sali√≥ Mal');
} catch{
    console.log('Hubo un error bastante grave...');
}